services:
  db:
    image: postgres:16
    container_name: totum_postgres
    restart: always
    environment:
      POSTGRES_USER: totum_user
      POSTGRES_PASSWORD: totum_user
      POSTGRES_DB: totum_db
    ports:
      - "5432:5432"
    volumes:
      - totum_pgdata:/var/lib/postgresql/data

volumes:
  totum_pgdata:
